### PR TITLE
Added Microsoft SQL Server example

### PR DESCRIPTION
**Pull request by amitkarpe**
## what
* Added Microsoft SQL Server example

## why
* There was MySQL RDS example but nothing for MSSQL

### CODE REVIEW

**Comment by amitkarpe** [comment]
Can someone please review this PR?

**Comment by joe-niland** [comment]
Hi @amitkarpe 
Saw your message on Slack.
This PR looks fine at a glance.
We're just waiting on some upstream changes before reviewing and running the automated tests.

**Comment by amitkarpe** [comment]
Anything I should add here?

**Comment by joe-niland** [comment]
@amitkarpe do you mind merging in master?

**Comment by amitkarpe** [comment]
Merge is blocked which needs at least one approval.

**Comment by joe-niland** [comment]
@amitkarpe please rebase from master

**Review by Gowiem — APPROVED** [review]

**Comment by amitkarpe** [comment]
Thank you for your guidance.
@joe-niland and @Gowiem

**Pull request merged**
