### PR TITLE
Support AWS Provider V5

### PR DESCRIPTION
**Pull request by max-lobur**
## what

- Support AWS Provider V5
    - Notable: ID output breaking (in regards to provider version compatibility) change https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-5-upgrade#resourceaws_db_instance

- Linter fixes

## why

Maintenance

## references

https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.0.0

### CODE REVIEW

**Comment by mihaiplesa** [comment]
@max-lobur has this one been abandoned?

**Comment by max-lobur** [comment]
No I just didn't have time to merge all of these. I will fix today

**Pull request merged**
