### PR TITLE
Setting ca_cert_identifier default value to null

### LINKED ISSUE #114: Creating RDS in newer regions errors but RDS is created
## Describe the Bug
Creating RDS in newer regions errors but RDS is still created. 

## Expected Behavior
Either the terraform to error and the RDS to not be created or the terraform to give a warning and the RDS to be created.

## Steps to Reproduce
Create an RDS in a newer region (Confirmed to happen on `me-south1` , `eu-south-1` )

Example: 
```
module "rds_instance" {
  source            = "git::https://github.com/cloudposse/terraform-aws-rds.git?ref=tags/0.35.1"
  enabled           = true
  storage_type      = "gp2"                             # Not req but default to magnetic otherwise
  engine            = "postgres"                        # req
  allocated_storage = 100                               # req
  database_name     = var.database_name                 # req
  database_user     = var.database_user                 # req
  database_password = random_password.pg_passwd.result  # req
  database_port     = 5432                              # req
  multi_az          = false                             # Not req, here for possible future use
  vpc_id            = module.vpc.vpc_id                 # req
  subnet_ids        = module.subnets.private_subnet_ids # req
  storage_encrypted = true                              # Not req but default to false otherwise
  snapshot_identifier = null

  engine_version     = var.engine_version    
  db_parameter_group = var.db_parameter_group
  instance_class     = var.instance_class     # req

  apply_immediately       = false
  maintenance_window      = "Mon:03:00-Mon:04:00"
  skip_final_snapshot     = true
  backup_retention_period = 7
  backup_window           = "22:00-03:00"

  attributes = ["psql"]
  context    = module.label.context
}
```
The error: 

```╷
│ Error: error modifying DB Instance (foo-bar-db-469034-psql): CertificateNotFound: Certificate not found: rds-ca-2019
│       status code: 404, request id: c1b5bac9-b9e1-4243-a747-33a48b408cbd
│ 
│   with module.rds_instance.aws_db_instance.default[0],
│   on .terraform/modules/rds_instance/main.tf line 22, in resource "aws_db_instance" "default":
│   22: resource "aws_db_instance" "default" {
│ 
```

But it has created the db with the default cert.

image

The module either needs to use the right default cert so it does not error, or as it is using the default in the end not error out the deployment

### PR DESCRIPTION
**Pull request by nnsense**
## what
Setting ca_cert_identifier default value to null, leaving its resolution up to the AWS resource.

## why
Creating RDS in newer regions such as `eu-south-1`, `ap-east-1`, `me-south-1`, `af-south-1` errors but RDS instance is still created. The default CA certificate ID (`rds-ca-2019`), which is valid across most of the regions, has a different format on these, see: https://github.com/cloudposse/terraform-aws-rds/issues/114#issuecomment-845826580

## references
* https://github.com/cloudposse/terraform-aws-rds/issues/114
* `closes #114`

### CODE REVIEW

**Comment by Gowiem** [comment]
@nnsense thanks for the contribution as always -- it seems our got stuck which is an annoying occurrence. Mind doing the following to bump that?

```
git commit --allow-empty -m "Trigger CI"
git push
```

**Comment by nnsense** [comment]
Hi @Gowiem is there anything else I should do?

**Review by Gowiem — APPROVED** [review]

**Pull request merged**
