### PR TITLE
Clarify description of db_parameter_group

### PR DESCRIPTION
**Pull request by yariksheptykin**
Documentation of the `db_parameter_group` variable is somewhat obscure with regard to possible values it intakes. It actually expects a name of DB parameter group **family**, which can be one of many pre-defined families provided by AWS. The list of supported families is quite hidden in AWS Documentation so I suggest placing a link to the right place stright into the variable description.

### CODE REVIEW

**Review by maximmi — APPROVED** [review]
@yariksheptykin thanks for contribution

**Comment by yariksheptykin** [comment]
> @yariksheptykin thanks for contribution

Sure. Thanks for taking time to get this landed, @maximmi !

**Pull request merged**
