### PR TITLE
Allow setting monitoring_role_arn

### PR DESCRIPTION
**Pull request by deiga**
## what
- Allowed to configure `monitoring_role_arn`

## why
- "Error: Error creating DB Instance: InvalidParameterCombination: A MonitoringRoleARN value is required if you specify a MonitoringInterval value other than 0."
- Apparenty the ARN must be set, if the monitoring interval is being set

## references
- closes https://github.com/cloudposse/terraform-aws-rds/issues/61

### CODE REVIEW

**Comment by tibbing** [comment]
Looks like a typo in the variable `monitorin_role_arn` -> `monitoring_role_arn`

**Comment by jamengual** [comment]
@deiga can you rebase please?

**Comment by jamengual** [comment]
@deiga look like this has been already added to the module, there is 0 files modified.

**Comment by deiga** [comment]
@jamengual Yup, seems so.

**Pull request closed without merging**
