### PR TITLE
Add `replicate_source_db`

### PR DESCRIPTION
**Pull request by nitrocode**
## what
* Add `replicate_source_db`

## why
* Create a read replica

## references
* Closes https://github.com/cloudposse/terraform-aws-rds/issues/113
* May remove the need to maintain https://github.com/cloudposse/terraform-aws-rds-replica

### CODE REVIEW

**Comment by adamantike** [comment]
@nitrocode, please take into account that some variables must be set as optional now, and only be checked for a provided value when `replicate_source_db` is not set. According to [`aws_db_instance` docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance), the ones that are optional for DB replicas are:

* `allocated_storage`
* `engine`
* `password`
* `username`

**Comment by nitrocode** [comment]
@adamantike thank you. I made `allocated_storage` and `engine` optional.

However it looks like `database_user` and `database_password` already have a default set. Are you saying that these should be set to `null` instead of an empty string ?

https://github.com/cloudposse/terraform-aws-rds/blob/cb41a4c878df92d03efa845323f9704078417c43/variables.tf#L36-L38

https://github.com/cloudposse/terraform-aws-rds/blob/cb41a4c878df92d03efa845323f9704078417c43/variables.tf#L42-L44

**Comment by adamantike** [comment]
It seems that, when `replicate_source_db` is set, provider code doesn't check the value of `username`, and uses `d.GetOk` to check the value of `password`, filtering out empty values. I think it should be fine to proceed as this PR is right now, though I haven't tested it with a real DB instance :+1:

Reference: https://github.com/hashicorp/terraform-provider-aws/blob/1983631376fc8eb37a8a627bd225b70b44df3c7f/aws/resource_aws_db_instance.go#L610

**Comment by nitrocode** [comment]
@adamantike try it if you can. Something like this should work.

```hcl
module "rds" {
  source = "git::github.com:cloudposse/terraform-aws-rds.git?ref=replicate_source_db"

  # ...
}
```

**Comment by adamantike** [comment]
@nitrocode, I have tested it, and works as expected! The only issues I found are related to upstream checks being made by the AWS provider, which I think shouldn't be replicated in this module to avoid unneeded complexity. Examples:

> Error: Error creating DB Instance: InvalidDBInstanceState: Automated backups are not enabled for this database instance. To enable automated backups, use ModifyDBInstance to set the backup retention period to a non-zero value.

It would require a `data.aws_db_instance` block to check that the primary database instance being referenced by `var.replicate_source_db` has `backup_retention_period > 0`.

> Error: Error creating DB Instance: DBSubnetGroupNotAllowedFault: DbSubnetGroupName should not be specified for read replicas that are created in the same region as the master

Same, and would also require comparing regions between primary/replica.


I think this is good to go in its current state! :rocket:

**Comment by razorsedge** [comment]
This is working for me as well.

**Comment by nitrocode** [comment]
@razorsedge @adamantike

This has been released as https://github.com/cloudposse/terraform-aws-rds/releases/tag/0.38.0.

Thanks for your input!

**Comment by c4milo** [comment]
Any example of how to wire it all together?

**Pull request merged**
