### PR TITLE
storage_encrypted default value changed to true

### PR DESCRIPTION
**Pull request by maximmi**
## what
* BridgeCrew compliance checks fix
* readme updated
* default behaviour changed: `RDS Instance Encryption` enabled by default

## why
* To be able to position our modules as standards compliant
* stay in sync with code
* To comply BridgeCrew check

## references
* https://docs.bridgecrew.io/docs/general_4

### CODE REVIEW

**Comment by Gowiem** [comment]
@maximmi looks like resources are sticking around in the test account -- 
image

Should likely run again after aws-nuke clears those up or go into that account and delete them manually.

**Review by osterman — APPROVED** [review]

**Pull request merged**
