### PR TITLE
Add option to define character set

### LINKED ISSUE #70: Add `charset_name` option
## Describe the Feature

RDS module should provide a option for specifying database character set.

## Expected Behavior

Setting `character_set_name` to, for example, `utf8mb4` for `engine_name = "mariadb"` craetes a MariaDB instance with `utf8mb4` charset instead of [`latin1`](https://mariadb.com/kb/en/setting-character-sets-and-collations/).

## Use Case

Pimcore has a [hard requirement](https://pimcore.com/docs/6.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/DB_Setup.html#page_Database-Setup) for its datbase to use `utf8mb4`-charset. Inability to set this charset makes this module incompatible with pimcore, which is unfortunate.

## Describe Ideal Solution

Introduce a new optional variable `database_charset` and pass it through to `db_instance` resource as [documented here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#character_set_name)

## Alternatives Considered

One alternative considered is forking this repo and adding the option in a fork. But that's unnecessary code duplication and maintenance. Would be better to add this to the official module.

### PR DESCRIPTION
**Pull request by yariksheptykin**
Closes #70

### CODE REVIEW

**Comment by maximmi** [comment]
@yariksheptykin please, rebase the code

**Comment by yariksheptykin** [comment]
Hi @maximmi , could you take a look at this MR before it becomes stale again?

**Comment by yariksheptykin** [comment]
Closing merge request because there does not seem to be much interest in this work.

**Review by jamengual — APPROVED** [review]

**Comment by Gowiem** [comment]
Thanks for the contribution @yariksheptykin -- we appreciate it! Released as [0.37.0](https://github.com/cloudposse/terraform-aws-rds/releases/tag/0.37.0).

**Pull request merged**
